### ISSUE TITLE
Able to change the size of the notification alert

### ISSUE THREAD

**Issue by chrisduong** [atom/notifications#109]
Hi,

I wish I could change the size when the notification show up, it is quite large, that I cannot see to type correctly. I have to wait it is gone.

For e.g. When I commit with **"git-plus"**, new pane is created for typing the commit message, however the notification alert hide it, I cannot type right away.

Thanks

**Comment by ericeslinger** [comment]
FWIW, I ended up overriding a bunch of the notification css in my own personal atom stylesheet. The close-delay can't be configured by css, but I changed atom-notifications to have left: 0 instead of right: 0, and atom-notification to have float:left instead of float:right. That way they pop up over my filetree instead of on top of my actual work area. I also changed most of the dimensions from px values to em values so the popup scaled more smoothly based on font size.

**Comment by damieng** [comment]
The recommended Atom way of customizing the UI is to use CSS.  A configuration option would instead break all existing themes that customize notifications today.
