### ISSUE TITLE
Error: Please enter a valid URL to shorten

### ISSUE THREAD

**Issue by Ben3eeE** [atom/notifications#132]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

[Shortening the URL](https://github.com/atom/notifications/blob/master/lib/notification-issue.coffee#L42) of an exception fails with the response

```
{
  readyState: 4,
  responseText: "Error: Please enter a valid URL to shorten",
  status: 400,
  statusText: "error"
}
```

I am also unable to click the `Create issue on the [package] package` button on the notification.
### Steps to Reproduce
1. Open Atom in safe mode using `atom --safe` from `cmd.exe`.
2. Open the developer tools with <kbd>Ctrl-Shift-i</kbd>
3. Make Atom throw an exception. I used the steps described in the [selectedEntry.expand](https://github.com/atom/tree-view/issues/921#issuecomment-239305499) issue.
4. Keep an eye on the console in the developer tools. When the duplicate issue is found on the `tree-view` package this error is shown in the console.

**Gist of URL that is shortened:** https://gist.github.com/Ben3eeE/610d8a1459f1b6021b95105dde898b61

**Gif of reproduction:**
![notifications error](https://cloud.githubusercontent.com/assets/1058982/19494173/1bf38ea2-957e-11e6-94a6-5e086c3b24ba.gif)

**Full stacktrace:**
![pasted_image_at_2016_10_18_09_14_pm](https://cloud.githubusercontent.com/assets/1058982/19494084/b764f764-957d-11e6-8db5-e82b4b654231.png)

**Expected behavior:** Only the exception that Atom throws to be in the console.

**Actual behavior:** Two additional errors are shown.

**Reproduces how often:** 100%, I tried with 3 different exceptions. The two Pane has been destroyed exceptions and the SelectedEntry.expand exception.

**Refs:** https://github.com/atom/notifications/issues/129
### Versions

Windows 10 x64 Anniversary.
###### atom --version

```
Atom    : 1.12.0-beta2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```
###### apm --version

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.10.1.windows.1
visual studio 2015
```

**Comment by 50Wliu** [comment]
I can confirm this on Windows 10 x64.

**Comment by 0xB767B** [comment]
Same on Ubuntu 16.10

atom --version:

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm --version:

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

**Comment by borisovg** [comment]
+1 on Debian Sid

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by damieng** [comment]
Yeah even the specs are running into this. Either our payload got too big at one point and the tests are inadequate or perhaps is.gd changed their api. Investigating.

**Comment by 50Wliu** [comment]
The packages listing was changed in I think 1.8.0 to also list all core packages whereas before it would only list community ones.  Might want to look into that.

**Comment by damieng** [comment]
We have two issues here;

1. Sometimes is.gd doesn't like our payload - and it's not just because of size
2. Most of our payloads are too big for a GET request

The second is a real problem. Even when is.gd happily accepts it and gives notifier a is.gd link to follow we get redirected to our original GH issue url (not sure why we take this shortcut unless it's to avoid problems with passing big links directly to browsers)...

The issue URL is obviously a GET and has the stuff in the URL... We only have 2036 bytes to play with in a URL and the GH create issue link takes 40 bytes so really we have about 1990 bytes for our issue payload.

Right now on my machine during the tests my issue payload is ~8400 bytes before URL encoding, about 10,000 bytes after.

We're out by a big factor here so here's what I think we should do;

1. Direct link from notifier to the GH create issue page with only the title filled in and a minimal header with instructions
2. Provide a copy-diagnostics-info button in Notifier that copies the stack trace, packages, config etc. so that the user can paste it into the issue

I know this is an extra step for people to report but I don't think for most people this is working right now unless maybe you have an absolute minimal set of core packages installed.



So we create a url with all the data encoded on it then post that to is.gd to create a shortcut.

**Comment by yvan-sraka** [comment]
+1 on an daily updated 64Bits ArchLinux

It was triggered at the same time as this issue: https://github.com/steelbrain/linter-ui-default/issues/362

**Comment by rsese** [comment]
> daily updated 64Bits ArchLinux

Thanks for reaching out!  It sounds like you're using an unofficial build or distribution of Atom?  Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or master branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about why [we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by yvan-sraka** [comment]
I understand, but my version of atom is not "nightly" or "custom" I use this version https://www.archlinux.org/packages/community/x86_64/atom/ with just the `linter` package, and the issue occurs every time I click the 'Conversation' button in the new GitHub PR integration: https://github.atom.io/

**Comment by damieng** [comment]
That version of Atom is exactly the reason the policy was introduced. The author believes he can just change the version of Electron he uses for Atom without consequence.

Here's an example of what's ACTUALLY required to upgrade electron. https://github.com/atom/atom/pull/12696 - it is 407 commits across 88 files.

**Comment by OvermindDL1** [comment]
Got this issue using the official Beta channel rpm from https://atom.io/beta and one of the plugins is throwing an exception, but clicking to create the exception is causing the browser to open and search for this.
