### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by whoughton** [atom/notifications#161]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.67.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At .../atom/packages/go-get/lib/manager.js:63

TypeError: Cannot read property 'length' of undefined
    at Manager.getLocatorOptions (/packages/go-get/lib/manager.js:63:51)
    at Manager.performGet (/packages/go-get/lib/manager.js:250:49)
    at NotificationElement.onDidClick (/packages/go-get/lib/manager.js:352:30)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:135:48)
```

### Commands

```
  2x -1:09.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
atom-alignment 0.13.0 
atom-beautify undefined 
autocomplete-go 1.3.0 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
file-icons 2.1.8 
git-history 3.3.0 
git-plus 7.9.3 
go-config 1.2.4 
go-get 2.1.1 
go-oracle 0.2.1 
go-rename 0.3.0 
gofmt 1.2.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.67.0 
language-graphql 0.9.0 
language-haml 0.25.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-rspec 0.6.2 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.23.0 
linter 2.2.0 
linter-js-standard 3.9.1 
linter-ui-default 1.6.2 
merge-conflicts 1.4.5 
minitest-snippets 0.2.0 
monokai 0.24.0 
multi-wrap-guide 0.28.4 
nuclide undefined 
nuclide-format-js 0.0.36 
open-recent 5.0.0 
package-sync 1.1.0 
pigments 0.39.1 
sort-lines 0.14.0 
standard-formatter 2.8.0 
standardjs-snippets 2.6.0 
Sublime-Style-Column-Selection 1.7.4 
todo-show 1.11.0 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
Zen 0.18.0 
```

I get this all the time but honestly have no real clue what is causing it.

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [go-get](https://atom.io/packages/go-get) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
