### ISSUE TITLE
Key to press to close notification is missing

### ISSUE THREAD

**Issue by willnwhite** [atom/notifications#166]
### Description

You can press a key to close notifications (esc by default), but this is not easy to discover as the notification doesn't say so. I was growing very tired of clicking on error messages in prettier.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by willnwhite** [comment]
I thought the template is for a bug report, not a feature request. I think all the information needed for the feature is in my comment. I'm asking for "esc" (or whatever key the user has bound to close notifications) to be shown in the notification (as the "X" is).

**Comment by 50Wliu** [comment]
The template is needed for all issues, including enhancements.  We _require_ the issue template so that there is no ambiguity in what the issue is about.
