### ISSUE TITLE
Exception reporting: possible to add ternjs crash reporting?

### ISSUE THREAD

**Issue by Zireael** [atom/notifications#199]
## Summary

For plugin crashes Atom has feature to automatically report crashes as Github isse. However I've been having crashes of ternjs that don't seem to be covered by that feature.
Is it possible to add ternjs as a library monitored for crashes?

## Motivation

Users that experience crashes of ternjs don't have easy way to report issue.

## Describe alternatives you've considered

1) Ignore the issue: constant popup windows from ternjs crashes get in the way of my work
2) disable/remove ternjs: I would rather not remove parts of Atom in a hacky way, even if Atom is supposed to be hackable. It's actually quite useful, until it starts crashing.

## Additional context

Video showing error popups with non-reportable crashes:
https://streamable.com/vw1qn

Users first reported having issues with ternjs 1.5 years ago, but without automatic logging provided, we were not able to receive a fix:
https://github.com/tststs/atom-ternjs/issues/328

**Comment by Arcanemagus** [comment]
Thanks for contributing!

As you have already figured out it appears that this is being caused by the [atom-ternjs](https://github.com/tststs/atom-ternjs) package, not Atom itself.

The uncaught exception handling you are talking about is for exceptions that the package itself isn't handling and are attempting to bubble up to Atom itself. From the issue you linked and the video it appears that the `atom-ternjs` package _is_ catching these exceptions, and then using `atom.notifications.addError` to notify the user about it.

You'll need to have the package author either fix the issue that is throwing the error, or have better handling of the error but this doesn't appear to have anything to do with Atom itself other than it being a package for Atom.

----

It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
