### ISSUE TITLE
Close button of issues rerorter doesn't have margins

### ISSUE THREAD

**Issue by izuzak** [atom/notifications#21]
_From @alexandernst on January 2, 2015 11:16_

The text of the error/bug is shown right under the close button:

![Image of Close button](http://ibin.co/1mkcqH3Jxzsu)

_Copied from original issue: atom/tree-view#301_

**Comment by simurai** [comment]
I can't reproduce this issue. There should always be a (short) message at the top so that the close button isn't covering the error text.

![screen shot 2015-01-14 at 10 03 59 pm](https://cloud.githubusercontent.com/assets/378023/5739192/8b78ed34-9c39-11e4-9652-409394ba5df2.png)

There might errors without a message, but even then there should be some padding that keeps the close button above the error text.

![screen shot 2015-01-14 at 10 12 06 pm](https://cloud.githubusercontent.com/assets/378023/5739256/bedd6690-9c3a-11e4-9aa3-d8a155f208b2.png)

@benogle Have you ever come across this issue?

**Comment by benogle** [comment]
@simurai it happens when scrolling.

**Comment by simurai** [comment]
@benogle Hmmm.. still can't reproduce it. The close button scrolls too:

![scrolling](https://cloud.githubusercontent.com/assets/378023/5810649/3a1648e4-a08d-11e4-8cd1-bb2d0de720d4.gif)
 
Does it stay fixed for you? If so, maybe some weird rendering issue that only happens in certain cases?

**Comment by benogle** [comment]
Maybe when you have a vary tall screen, the max-height on the `atom-notification` element kicks in before the container scroller.

**Comment by simurai** [comment]
Hey, that's it! :+1:

If the error message is very long, then the `800px` min-height kicks in. Actually, the min-height there is only used for the animation. I'll add another one to make only the error message scroll and not the whole notification.
