### ISSUE TITLE
Invalid version logged for certain packages under the Atom org

### ISSUE THREAD

**Issue by kevinsawicki** [atom/notifications#74]
Looks like the test for `isCore` on https://github.com/atom/notifications/blob/5ede904400c9ed2c7047d195884309996aa4a38b/lib/user-utilities.coffee#L175 uses the repository URL but there are packages in the org. that aren't shipped with Atom such as `sort-lines` and the following error is logged when that packages generates an uncaught exception:

```
TypeError: Invalid Version: undefined
  at new SemVer (/Users/kevin/github/notifications/node_modules/semver/semver.js:262:11)
  at SemVer.compare (/Users/kevin/github/notifications/node_modules/semver/semver.js:312:13)
  at compare (/Users/kevin/github/notifications/node_modules/semver/semver.js:535:31)
  at Function.gte (/Users/kevin/github/notifications/node_modules/semver/semver.js:584:10)
  at /Users/kevin/github/notifications/lib/user-utilities.coffee:183:49
```

**Comment by izuzak** [comment]
Ahh, totally forgot about that case when I was working on https://github.com/atom/notifications/pull/52.

:bulb: instead of checking if the package is in the org, we could use the same check as the one [here](https://github.com/atom/notifications/blob/5ede904400c9ed2c7047d195884309996aa4a38b/lib/user-utilities.coffee#L159) and see if it's listed in the package.json under packageDependencies? That seems like a better way to check if it's a core package.

**Comment by kevinsawicki** [comment]
:+1:
